package marcinlowercase.a.core.constant
object DefaultSettingValues {
    const val PADDING = 5f
    const val CORNER_RADIUS = 30f
    const val SINGLE_LINE_HEIGHT = 90f
    const val MAX_LIST_HEIGHT = 2f
    const val URL = "https://oo1.studio"
    const val SHOW_SUGGESTIONS = false
    const val ANIMATION_SPEED = 300f
    const val IS_SHARP_MODE = false
    const val IS_DESKTOP_MODE = false
    const val CURSOR_CONTAINER_SIZE = 50f
    const val CURSOR_POINTER_SIZE = 5f
    const val CURSOR_TRACKING_SPEED = 1.75f
    const val BACK_SQUARE_IDLE_OPACITY = 0.2f
//    const val HIGHLIGHT_COLOR = 0xFFBA160C.toInt()
    const val HIGHLIGHT_COLOR = 0xFF0010FF.toInt()
    const val IS_AD_BLOCK_ENABLED = true
    const val IS_FULLSCREEN_MODE = false
    const val CLOSED_TAB_HISTORY_SIZE = 10f
    const val SEARCH_ENGINE = 0
    const val OPTIONS_ORDER = "TABS_PANEL,SHARP_MODE,REOPEN_TAB,FULLSCREEN,DESKTOP_MODE,ROTATE,FIND_IN_PAGE,DOWNLOAD_PANEL,CLOSE_ALL_TABS,SETTINGS"
    const val SETTINGS_ORDER = "SORT_BUTTONS,ADBLOCK,SUGGESTIONS,SEARCH_ENGINE,DEFAULT_URL,HISTORY_SIZE,CORNER_RADIUS,PADDING,SINGLE_LINE_HEIGHT,MAX_LIST_HEIGHT,HIGHLIGHT_COLOR,ANIMATION_SPEED,CURSOR_SIZE,CURSOR_SPEED,BACK_SQUARE_OPACITY,RESET_SETTINGS,PRIVACY_POLICY"
    const val HIDDEN_OPTIONS = ""
}